name: "ðŸ“¦ Release to PyPI"

on:
  workflow_dispatch:
  schedule:
    - cron: "51 23 * * *"

jobs:
  call-pypi-release:
    name: "ðŸ¤™ Call PyPI release workflow"
    uses: clamsproject/.github/.github/workflows/sdk-helper-publish-daily.yml@main
    with:
      pypi_dist_name: clams-utils
    secrets: inherit

